import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Lock, ShieldAlert } from "lucide-react";
import { motion } from "framer-motion";

interface ArenaUnlockGateProps {
  onUnlock: () => void;
}

export default function ArenaUnlockGate({ onUnlock }: ArenaUnlockGateProps) {
  const [agreed, setAgreed] = useState(false);

  const canUnlock = agreed;

  const handleUnlock = () => {
    if (!canUnlock) return;
    onUnlock();
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.2 }}
      className="premium-card p-5 md:p-6 space-y-5"
    >
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
          <Lock className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h2 className="text-base font-bold text-foreground">
            Open Full Evaluation
          </h2>
          <p className="text-xs text-muted-foreground">
            Detailed analysis of your psychological profile
          </p>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="space-y-3 border-t border-border/50 pt-4">
        <div className="flex gap-2.5 text-xs text-muted-foreground leading-relaxed">
          <ShieldAlert className="w-4 h-4 text-destructive flex-shrink-0 mt-0.5" />
          <p>
            This evaluation is generated by AI and is intended for{" "}
            <span className="text-foreground font-medium">
              educational and self-awareness purposes only
            </span>
            . It does not constitute financial advice, a psychological
            diagnosis, or any form of professional recommendation. Results may
            not be fully accurate and should not be used as a basis for trading
            decisions.
          </p>
        </div>

        {/* Agreement Checkbox */}
        <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/30 border border-border">
          <Checkbox
            id="eval-agree"
            checked={agreed}
            onCheckedChange={(v) => setAgreed(v === true)}
            className="mt-0.5"
          />
          <label
            htmlFor="eval-agree"
            className="text-sm text-foreground cursor-pointer select-none leading-snug"
          >
            I understand this is an AI-generated evaluation for educational
            purposes only. I accept that no financial or psychological advice is
            being given.
          </label>
        </div>
      </div>

      {/* CTA Button */}
      <Button
        onClick={handleUnlock}
        disabled={!canUnlock}
        className="w-full h-11 text-sm font-semibold disabled:opacity-40"
      >
        <Lock className="w-4 h-4 mr-2" />
        Unlock Full Evaluation
      </Button>
    </motion.div>
  );
}
